### ISSUE TITLE
seems not to work anymore

### ISSUE THREAD

**Issue by erwan-joly** [morsisko/NosTale-Gfless#1]
it seems like this method doesn't work anymore... 
gameforge_client_api64.dll
gameforge_client_api.dll
are in my directory but i still get the gf init failed...

i tested with and without env key...

the client doesn't even seems to send anything on the named pipe except when launched from the official launcher

any idea what changed ?

**Comment by erwan-joly** [comment]
NVM i found the issue the gameforge client in case you launch it from a local copy don't use your current directory but redownload the full launcher in program files

**Comment by erwan-joly** [comment]
some info: client only work if it's under C:\Program Files (x86)\Nostale\LANG

**Comment by morsisko** [comment]
I think it is **probably** due to fact that you have set the "_TNT_CLIENT_APPLICATION_ID" var, if you comment it and copy the .dll file to game folder, it should work anywhere

**Comment by erwan-joly** [comment]
I don’t my launcher copy the dll to avoid this. But need to retry as I changed a bit the launcher...
