### ISSUE TITLE
outdated client issue

### ISSUE THREAD

**Issue by McIks** [morsisko/NosTale-Gfless#2]
hello,
I am not sure I have an error with "outdated nostale client". Looks like it's connecting well (whole generating tokens part etc) but after openning NosTale client it looks like it's outdated...but it is not. 

any suggestion what can be wrong?

greetings

**Comment by morsisko** [comment]
Are you trying to connect to private or official server? Maybe your client is ineed outdated? For me it still works like charm.

**Comment by McIks** [comment]
@morsisko I am trying to connect to official (PL) server. Client is not outdated. When I run gameforge it's working perfectly.

**Comment by morsisko** [comment]
Are you sure you don't have multiple NosTale installations on your PC? Are you sure that the path to the NostaleClientX.exe is correct?
